src/Entity/TimeLog.php
<?php

namespace App\Entity;

use App\Repository\TimeLogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TimeLogRepository::class)
 */
class TimeLog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $work_day;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start_time;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_time;

    /**
     * @ORM\ManyToOne(targetEntity=Project::class, inversedBy="timeLogs")
     */
    private $project;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWorkDay(): ?\DateTimeInterface
    {
        return $this->work_day;
    }

    public function setWorkDay(\DateTimeInterface $work_day): self
    {
        $this->work_day = $work_day;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(?\DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(?\DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }
}

src/Form/TimeLogType.php
<?php

namespace App\Form;

use App\Entity\TimeLog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class TimeLogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('work_day')
            ->add('start_time')
            ->add('end_time')
            ->add('project')
        ;
        $builder->addEventListener(FormEvents::SUBMIT, function(FormEvent $event) {
            $data = $event->getData();
            $form = $event->getForm();

            if ($data->getEndTime()) {
                $duration = $data->getEndTime()->getTimestamp() - $data->getStartTime()->getTimestamp();
                $data->setDuration($duration);           
                $event->setData($data);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TimeLog::class,
        ]);
    }
}

src/Controller/TimeLogController.php
<?php

namespace App\Controller;

use App\Entity\TimeLog;
use App\Form\TimeLogType;
use App\Repository\TimeLogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class TimeLogController extends AbstractController
{
    /**
     * @Route("/", name="time_log_index", methods={"GET"})
     */
    public function index(TimeLogRepository $timeLogRepository): Response
    {

        $latest_time_log = $timeLogRepository->findBy(array(),array('id'=>'DESC'),1,0);
        $monthly_report = $timeLogRepository->monthlyReport();
        $daily_work_avg = $timeLogRepository->getDailyAverage();

        return $this->render('time_log/index.html.twig', [
            'time_logs' => $timeLogRepository->findAll(),
            'latest' => reset($latest_time_log),
            'monthly_report' => $monthly_report,
            'daily_work_avg' => $daily_work_avg,
        ]);
    }

    /**
     * @Route("/start", name="time_log_start", methods={"GET"})
     */
    public function start(TimeLogRepository $timeLogRepository): Response
    {

        $latest_time_log =  $timeLogRepository->findBy(array(),array('id'=>'DESC'),1,0);
        $latest_time_log = reset($latest_time_log);
        if($latest_time_log&&!$latest_time_log->getEndTime()){
            throw new \Exception("A work has been already started! You must stop it first.");
        }

        $entityManager = $this->getDoctrine()->getManager();

        $time_log = new TimeLog();
        $time_log->setStartTime(new \DateTime());
        $time_log->setWorkDay(new \DateTime());

        // tell Doctrine you want to (eventually) save the Product (no queries yet)
        $entityManager->persist($time_log);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();
        return $this->redirect($this->generateUrl('time_log_index'));
    }

    /**
     * @Route("/end", name="time_log_end", methods={"GET"})
     */
    public function end(TimeLogRepository $timeLogRepository): Response
    {
        $latest_time_log = $timeLogRepository->findBy(array(),array('id'=>'DESC'),1,0);
        $latest_time_log = reset($latest_time_log);
        if(!$latest_time_log||!is_null($latest_time_log->getEndTime())){
            throw new \Exception("You must start a new work first.");
        }
        $entityManager = $this->getDoctrine()->getManager();
        $latest_time_log->setEndTime(new \DateTime());
        $duration = $latest_time_log->getEndTime()->getTimestamp() - $latest_time_log->getStartTime()->getTimestamp();
        $latest_time_log->setDuration($duration);

        // tell Doctrine you want to (eventually) save the Product (no queries yet)
        $entityManager->persist($latest_time_log);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        return $this->redirect($this->generateUrl('time_log_index'));
    }

    /**
     * @Route("/{id}/edit", name="time_log_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TimeLog $timeLog): Response
    {
        $form = $this->createForm(TimeLogType::class, $timeLog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('time_log_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('time_log/edit.html.twig', [
            'time_log' => $timeLog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="time_log_delete", methods={"POST"})
     */
    public function delete(Request $request, TimeLog $timeLog): Response
    {
        if ($this->isCsrfTokenValid('delete'.$timeLog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($timeLog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('time_log_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/time_log/_delete_form.html.twig
<form method="post" action="{{ path('time_log_delete', {'id': time_log.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ time_log.id) }}">
    <button class="btn btn-warning btn-sm">Delete</button>
</form>

templates/time_log/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/time_log/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TimeLog{% endblock %}

{% block body %}
    <h1>Edit TimeLog</h1>

    {{ include('time_log/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('time_log_index') }}">back to list</a>

    {{ include('time_log/_delete_form.html.twig') }}
{% endblock %}

templates/time_log/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TimeLog index{% endblock %}

{% block body %}

<h1>Average Daily Work: (Hours) {{ daily_work_avg ? daily_work_avg|date('H:i:s', '+00:00 GMT') : "No data"  }}</h1>
<br> 
<h1>Report Monthly</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Work Hours</th>
            </tr>
        </thead>
        <tbody>
        {% for mr_item in monthly_report %}
            <tr>
                <td>{{ mr_item.month }}/{{ mr_item.year }}</td>
                <td>{{ mr_item.d_hours  }}:{{ mr_item.duration|date('i:s', '+00:00 GMT')  }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">Not enough data</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<br>
    <h1>TimeLog</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Work Day</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Project</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for time_log in time_logs %}
            <tr>
                <td>{{ time_log.workDay ? time_log.workDay|date("d/M/Y") : '' }}</td>
                <td>{{ time_log.startTime ? time_log.startTime|date('d/M H:i') : '' }}</td>
                <td>{{ time_log.endTime ? time_log.endTime|date('d/M H:i') : 'In Work' }}</td>
                <td>{{ time_log.endTime ? time_log.project : '' }}</td>
                <td><div class="btn-group" role="group">
                    <a class="btn btn-info btn-sm" href="{{ path('time_log_edit', {'id': time_log.id}) }}">Edit</a>
                    &nbsp;{{ include('time_log/_delete_form.html.twig') }}</div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% if not latest or latest.endTime is not null %}
    <a class="btn btn-success btn-lg" href="{{ path('time_log_start') }}">Start</a>
{% elseif latest.endTime is null %}
    <a class="btn btn-danger btn-lg" href="{{ path('time_log_end') }}">Stop</a>
{% endif %}
{% endblock %}